### ISSUE TITLE
Documentation about spine ordering

### ISSUE THREAD

**Issue by davidrizo** [humdrum-tools/vhv-documentation#6]
When a voice is split into two spines, the ordering does not follow the same principle used for staves. 

In [Multiple voices on a staff](https://doc.verovio.humdrum.org/humdrum/getting_started/#multiple-voices-on-a-staff), the example:
```
**kern
*M4/4
*^
2..gg	4b
.	4a
.	4g
.	4f
8ff	.
*v	*v
=
*-
```
clearly shows that the spine encoded at left is drawn as the top voice, and the one encoded at right is encoded as the bottom voice.

![image](https://user-images.githubusercontent.com/10772049/79331123-fe447d00-7f1a-11ea-947a-efee0d252472.png)

This is the opposite of how staves must be encoded, left spines mean bottom staves, and right spines mean top staves.

This issue is just a request for documenting it.

**Comment by craigsapp** [comment]
There is a note above that example that already explains this (bold text at end of quote):

> Spine split manipulators (*^) and spine merge manipulators (*v) are used to add or remove voices/layers on a staff. Note that the highest part on the staff will typically be left most **(opposite of the staff ordering from lowest to highest).**

:-)

Background:

The official Humdrum Toolkit documentation says that a Humdrum score is a 90 degree rotation of a traditional score.  This means that the bottom staff is at the left side of a Humdrum score and the top staff is on the right.  This also implies that the subspines should split so that the lower notes are on the left and higher are on the right.

However, there were no real-world examples of subspine orderings and the Humdrum Toolkit did not explicitly forbid flipping the ordering of the subspines, so I use a reversed interpretation from Humdrum which is reversed from most other conceptualization of the ordering of the staves/layers in other software.   This is somewhat related to PostScript versus SVG coordinates (where SVG coordinates seem backwards since they do not match to mathematical coordinate axes).  Humdrum orders the staves in a similar manner to SCORE, where the bottom staff on a page is staff 1.

You have probably noticed that the staff numbers in my scores are numbered backwards from the order of the spines in Humdrum, such as:

```
*staff2 *staff1
```

One reason I do this, is that I want to allow the Humdrum scores to be fully reversed from the official ordering, and these numbers would keep track of which score ordering the spines are given.  I should allow auto-detecting of the staff ordering in VHV/verovio so that the highest staff on the system is the left or right side of the spines according to which has the lowest staff number.

-----------------

> This issue is just a request for documenting it.

I did add a simpler multiple-staff example in the documentation:

<img width="882" alt="Screen Shot 2020-04-15 at 10 21 41" src="https://user-images.githubusercontent.com/3487289/79367549-e82ac280-7f02-11ea-9967-a8cc5398e57b.png">

Eventually I will allow for `*staff#` to control the system ordering of the staves (which should be relatively easy to implement)

This would make the following data render the same as the example:

```

**kern	**kern
*staff1	*staff2
*M4/4	*M4/4
=1	=1
4c	1C
4e	.
4g	.
4cc	.
=2	=2
4dd	1GG
4b	.
4f	.
4a	.
=3	=3
1g;	1C;
==	==
*-	*-
```

There is a tool/option called `extractx -r` in the Humdrum Extras toolset that allows reversing of the staves for a system.

**Comment by davidrizo** [comment]
Thanks :)
